### ISSUE TITLE
Getting All Channels Fails

### ISSUE THREAD

**Issue by sirk123au** [nwithan8/dizqueTV-python#93]
Trying this simple code to call all channels but i get the following error.

`from dizqueTV import API`
`DIZQUETV_URL = "http://localhost:8000"`
`dtv = API(url=DIZQUETV_URL)`
`print(dtv.channels)`

`Traceback (most recent call last):`
 ` File "test.py", line 9, in <module>`
`    print(dtv.channels)`
` File "/usr/local/lib/python3.8/dist-packages/dizqueTV/dizquetv.py", line 458, in channels`
`   return [Channel(data=channel, dizque_instance=self) for channel in json_data]`
`  File "/usr/local/lib/python3.8/dist-packages/dizqueTV/dizquetv.py", line 458, in <listcomp>`
 `  return [Channel(data=channel, dizque_instance=self) for channel in json_data]`
 ` File "/usr/local/lib/python3.8/dist-packages/dizqueTV/models/channels.py", line 303, in __init__`
 `   self._program_data = data.get('programs')`
`AttributeError: 'int' object has no attribute 'get'`

is it something that i am doing wrong?

**Comment by nwithan8** [comment]
This is a weird potential bug.
What version of the library are you using?

**Comment by sirk123au** [comment]
Latest 
`dizqueTV  1.5.0.0`

**Comment by nwithan8** [comment]
Turns out this is an actual bug with dizqueTV's API. Working with the developer to fix it, and will patch the API library afterwards. Thanks for bringing it to my attention.

**Comment by nwithan8** [comment]
Temporary patch: eb81cd5ba1ecb77ef82d469ee141f7a2a6088e74
