### ISSUE TITLE
Compatible with PlexAPI 4.11?

### ISSUE THREAD

**Issue by irodimus** [nwithan8/dizqueTV-python#99]
I've install PlexAPI 4.11 and get an incompatibility error with dizqueTV 1.5.0.4. Is this version still compatible or will dizqueTV-python require an update?

**Comment by nwithan8** [comment]
Can you elaborate on what the incompatible error is?

**Comment by irodimus** [comment]
This is what appears

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dizquetv 1.5.0.4 requires plexapi~=4.9.1, but you have plexapi 4.11.2 which is incompatible.
```
Just wanted to check if it would cause any issues. I did try to create a channel using one of the script so it appears to work.

**Comment by nwithan8** [comment]
This is because I have pinned the Plex dependency for this library. Let me check to make sure there's no compatibility issues, and I will tweak the pin to be less aggressive.
